#!/bin/bash
# ════════════════════════════════════════════════════════════════
# write-project-config.sh — 由 n8n 動態寫入專案的 testing.yml 和 .env
#
# 用法：
#   bash tests/scripts/write-project-config.sh \
#       <name> <local_path> <target_url> <php_version> [env_b64]
#
# 行為：
#   - local_path 為有效目錄 → 寫到 <local_path>/.testing/testing.yml + .env
#   - local_path 空或不存在 → 寫到 <ROOT>/.tmp-ephemeral/<name>/testing.yml
#     （registry 需指向 ephemeral 路徑；由 register-project.sh 處理）
#   - env_b64 為 base64 編碼的 .env 檔完整內容（選填）
#
# 輸出：
#   最後一行印出實際寫入的目錄（給 n8n 作為下一節點的輸入）
# ════════════════════════════════════════════════════════════════
set -euo pipefail

NAME="${1:-}"
LOCAL_PATH="${2:-}"
TARGET_URL="${3:-}"
PHP_VERSION="${4:-8.1}"
ENV_B64="${5:-}"

if [ -z "$NAME" ] || [ -z "$TARGET_URL" ]; then
    echo "用法：bash tests/scripts/write-project-config.sh <name> <local_path> <target_url> [php_version] [env_b64]" >&2
    exit 1
fi

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

# 自動補齊 yq（host 只需要 Docker）
source "$ROOT/tests/scripts/lib/bootstrap.sh"

# ─── 決定寫入目錄：有效 local_path → 真專案；否則 → ephemeral ──
# 不論模式，最終目錄結構都是 <registry_path>/.testing/testing.yml
# 這樣 run-project.sh 的 "$REG_PATH/.testing/testing.yml" 邏輯才對得上
if [ -n "$LOCAL_PATH" ] && [ -d "$LOCAL_PATH" ]; then
    REGISTRY_PATH="$LOCAL_PATH"
    MODE="project"
    EFFECTIVE_LOCAL_PATH="$LOCAL_PATH"
else
    REGISTRY_PATH="$ROOT/.tmp-ephemeral/$NAME"
    MODE="ephemeral"
    EFFECTIVE_LOCAL_PATH=""   # ephemeral 一律 URL-only
    [ -n "$LOCAL_PATH" ] && echo "⚠️  local_path 不存在：$LOCAL_PATH → 寫入 ephemeral" >&2
fi

CONFIG_DIR="$REGISTRY_PATH/.testing"
mkdir -p "$CONFIG_DIR"

# ─── 寫 testing.yml（schema v2）───
TESTING_YML="$CONFIG_DIR/testing.yml"
cat > "$TESTING_YML" <<EOF
# Auto-generated by write-project-config.sh
# 來源：n8n workflow（Form Trigger 或 Google Sheets）
schema_version: 2
project:
  name: $NAME
  target_url: $TARGET_URL
  local_path: "$EFFECTIVE_LOCAL_PATH"
  php_version: "$PHP_VERSION"
EOF

echo "  ✓ 寫入 $TESTING_YML"

# ─── 寫 .env（若有提供 base64 內容）───
if [ -n "$ENV_B64" ]; then
    ENV_FILE="$CONFIG_DIR/.env"
    echo "$ENV_B64" | base64 -d > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "  ✓ 寫入 $ENV_FILE（$(wc -l < "$ENV_FILE") 行）"
fi

# ─── ephemeral 清理：刪 7 天前沒動過的 ──
if [ "$MODE" = "ephemeral" ]; then
    EPHEMERAL_ROOT="$ROOT/.tmp-ephemeral"
    find "$EPHEMERAL_ROOT" -maxdepth 1 -mindepth 1 -type d -mtime +7 \
        -not -path "$CONFIG_DIR" \
        -exec rm -rf {} \; 2>/dev/null || true
fi

# ─── 輸出給下游（n8n register 節點）──
# 最後一行就是 registry 要記的 path（run-project.sh 會從這裡讀 .testing/testing.yml）
echo "$REGISTRY_PATH"
